blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/evansvl/vless-shopbot/discussions
    about: Please ask and answer questions here.
  - name: Telegram Support
    url: https://t.me/ukarshiev
    about: Get direct support via Telegram.
  - name: Email Support
    url: mailto:umid.t.karshiev@gmail.com
    about: Contact us directly via email.
